version: "3"

services:
  pg_rman:
    image: nexus.onstream-cloud.com/pg_rman
    user: "70:root"
    volumes:
      - /dockerdata/postgres/data:/pg_data:z
      - /dockerdata/postgres/backup:/backup:z
    networks:
      - dev-net
    environment:
      - PGHOST=postgres  
      - PGUSER=sonar  
      - PGDATABASE=postgres  
      - PGPASS=sonar  
      - PGPORT=5432  
networks:
  dev-net:
    external: true
