FROM nexus.onstream-cloud.com/alpine-base:v3.10

ARG RMAN_VER=1.3.8
ENV PACKAGE_URL https://github.com/ossc-db/pg_rman/archive/V${RMAN_VER}.tar.gz



WORKDIR /build

RUN apk --no-cache add postgresql-libs postgresql-dev linux-pam-dev \
                       libedit-dev zlib-dev \
    && apk add --no-cache --virtual build-dependencies \
                                    curl build-base \
    && echo ${PACKAGE_URL} \
    && curl -SL ${PACKAGE_URL} | \
       tar -zxv --strip-components=1 \
    && make \
    && make install \
    && cd / \
    && rm -rf /build \
    && apk del build-dependencies --purge

WORKDIR /
COPY ./entrypoint.sh /entrypoint.sh

ENV PGDATA /var/lib/postgresql/data
ENV BACKUP_PATH /var/lib/postgresql/data/backup
VOLUME ["/pg_data", "/backup"]

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/sh"]