version: "3"

services:
  pg_rman:
    image: nexus.onstream-cloud.com/pg_rman
    user: "70:root"
    volumes:
      - ./postgres:/pg_data
      - /host/path/to/backup:/backup
    networks:
      - dev-net
    environment:
      - PGHOST=postgres  
      - PGUSER=postgres  
      - PGDATABASE=postgres  
      - PGPASS=  
      - PGPORT=5432  
networks:
  dev-net:
    external: true
