version: '3'
services:
  sonarqube:
    image: nexus.onstream-cloud.com/sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro #主机时区
      - /dockerdata/sonar/conf:/opt/sonarqube/conf:Z #:Z 解决与 SELinux 相关的权限问题
      - /dockerdata/sonar/data:/opt/sonarqube/data:Z #:Z 解决与 SELinux 相关的权限问题
      - /dockerdata/sonar/extensions:/opt/sonarqube/extensions:Z #:Z 解决与 SELinux 相关的权限问题
      - /dockerdata/sonar/logs:/opt/sonarqube/logs:Z #:Z 解决与 SELinux 相关的权限问题
      - /dockerdata/sonar/bundled-plugins:/opt/sonarqube/lib/bundled-plugins:Z #:Z 解决与 SELinux 相关的权限问题
    networks:
      - sonar-net
  db:
    image: postgres:alpine   #postgres 镜像
    volumes:
      - /etc/localtime:/etc/localtime:ro #主机时区
      - /dockerdata/sonar/postgres:/var/lib/postgresql #将数据映射到对应的路径
    environment:
      - POSTGRES_PASSWORD=sonar  #密码
      - POSTGRES_USER:=sonar
    networks:
      - sonar-net

networks:
  sonar-net:
    driver: bridge

