version: '3'
services:
  sonarqube:
    image: nexus.onstream-cloud.com/sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro #主机时区
      - /dockerdata/sonar/conf:/opt/sonarqube/conf
      - /dockerdata/sonar/data:/opt/sonarqube/data
      - /dockerdata/sonar/logs:/opt/sonarqube/logs
      - /dockerdata/sonar/extensions:/opt/sonarqube/extensions
      - /dockerdata/sonar/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonar-net
  db:
    image: postgres:alpine   #postgres 镜像
    ports:
      - "5431:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro #主机时区
      - /dockerdata/sonar/postgres:/var/lib/postgresql/data #将数据映射到对应的路径
    environment:
      - POSTGRES_USER=sonar 
      - POSTGRES_PASSWORD=sonar  #密码
    networks:
      - sonar-net

networks:
  sonar-net:
    driver: bridge

