version: "3"

services:
  postgres:
    image: postgres:alpine   #postgres 镜像
    hostname: postgres   
    ports:
      - 5432:5432  #映射端口号
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/postgres/data:/var/lib/postgresql/data:Z #:Z 解决与 SELinux 相关的权限问题 #将数据映射到对应的路径
      - /dockerdata/postgres/backup:/var/lib/pgbackrest:Z
    environment:
      - POSTGRES_PASSWORD=postgres  #密码
      - POSTGRES_USER=postgres
    networks:
      - dev-net
networks:
  dev-net:
    external: true
