version: '3'

services:
  cluster-master:
    image: nexus.onstream-cloud.com/debian-sshd
    container_name: cluster-master
    hostname: cluster-master
    privileged: true
    ports:
      - "2221:22"
      - "19000:9000"
    volumes:
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro  #主机公钥。
      - /root/.ssh/id_rsa:/root/.ssh/id_rsa:ro    #master 私钥。
      - /root/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro   #cluster公钥。
      - /dockerdata/data/s1/data:/data/:Z
    networks:
      netgroup:
        ipv4_address: 172.18.0.2

  cluster-slave1 :
    image: nexus.onstream-cloud.com/debian-sshd
    container_name: cluster-slave1 
    hostname: cluster-slave1 
    privileged: true
    ports:
      - "2222:22"
      - "19001:9000"
    volumes:
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - /dockerdata/data/s2/data:/data/:Z
    networks:
      netgroup:
        ipv4_address: 172.18.0.3

  cluster-slave2 :
    image: nexus.onstream-cloud.com/debian-sshd
    container_name: cluster-slave2 
    hostname: cluster-slave2 
    privileged: true
    ports:
      - "2223:22"
      - "19002:9000"
    volumes:
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro 
      - /dockerdata/data/s3/data:/data/:Z
    networks:
      netgroup:
        ipv4_address: 172.18.0.4

  cluster-slave3 :
    image: nexus.onstream-cloud.com/debian-sshd
    container_name: cluster-slave3 
    hostname: cluster-slave3 
    privileged: true
    ports:
      - "2224:22"
      - "19003:9000"
    volumes:
      - /root/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - /dockerdata/data/s4/data:/data/:Z
    networks:
      netgroup:
        ipv4_address: 172.18.0.5
          
networks:
  netgroup:
    ipam:
      config:
      - subnet: 172.18.0.0/16
