version: '3'
services:
  gitlab:
    image:  'caeret/gitlab-ce-zh:12.1.0'
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.onstream-cloud.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "lzqy@onstream-cloud.com"
        gitlab_rails['smtp_password'] = "grnprubmexteecde"
        gitlab_rails['smtp_domain'] = "qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = "lzqy@onstream-cloud.com"
        gitlab_rails['gitlab_email_reply_to'] = "lzqy@onstream-cloud.com"
    ports:
      - '10080:80'
      - '10443:443'
      - '10022:22'
    volumes:
      - /etc/localtime:/etc/localtime:ro #主机时区
      - /dockerdata/gitlab/config:/etc/gitlab
      - /dockerdata/gitlab/data:/var/opt/gitlab
      - /dockerdata/gitlab/logs:/var/log/gitlab
    networks:
      - gitlab-net
  gitlab-ci:
    image: gitlab/gitlab-runner
    volumes:
      - /dockerdata/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro #主机时区
    networks:
      - gitlab-net
networks:
  gitlab-net:
    driver: bridge