version: '3'
services:
  gitlab:
    image:  'caeret/gitlab-ce-zh:12.1.0'
    hostname: gitlab     
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.onstream-cloud.com'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "lzqy@onstream-cloud.com"
        gitlab_rails['smtp_password'] = "grnprubmexteecde"
        gitlab_rails['smtp_domain'] = "exmail.qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = "lzqy@onstream-cloud.com"
        gitlab_rails['gitlab_email_reply_to'] = "lzqy@onstream-cloud.com"
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'postgres'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab123456'
        gitlab_rails['db_database'] = 'gitlab'
    ports:
      - '10080:80'
      - '10443:443'
      - '10022:22'
    volumes:
      - /dockerdata/gitlab/config:/etc/gitlab:Z
      - /dockerdata/gitlab/data:/var/opt/gitlab:Z
      - /dockerdata/gitlab/logs:/var/log/gitlab:Z
    networks:
      - dev-net
networks:
  dev-net:
    external: true