version: '3'

services:
    nginx:
        image: qiaogw/alpine-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dockerdata/nginx:/nginx:Z

