FROM qiaogw/alpine-base


RUN mkdir -p /nginx/www && \
    mkdir -p /nginx/log && \
    addgroup -g 82 -S nginx && \
    adduser -u 82 -S -D -g "" -G nginx nginx



RUN apk add --update nginx && \
    ln -sf /dev/stdout /nginx/log/access.log && \
    ln -sf /dev/stderr /nginx/log/error.log && \
    rm -rf /var/cache/apk/*


ADD rootfs/ /


EXPOSE 80 443
VOLUME ["/nginx"]

ENTRYPOINT []
CMD [ "nginx" ,"-c", "/nginx/conf/nginx.conf;" ]
