version: '3'

services:
    nginx:
        image: qiaogw/alpine-nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80"
            - "443:443"
            - "8088:8088"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dockerdata/nginx:/nginx:Z #:Z 解决与 SELinux 相关的权限问题
        networks:
            - nexus3_net1
networks:
  nexus3_net1:
    external: true