FROM qiaogw/alpine-base


RUN mkdir -p /nginx/www && \
    mkdir -p /nginx/log && \
    mkdir -p /run/nginx && \
    mkdir -p /var/run/nginx && \
    mkdir -p /nginx/conf/conf.d && \
    addgroup -g 82 -S nginx && \
    adduser -u 82 -S -D -g "" -G nginx nginx

RUN apk add --update nginx openssl && \
    ln -sf /dev/stdout /nginx/log/access.log && \
    ln -sf /dev/stderr /nginx/log/error.log && \
    rm -rf /var/cache/apk/*





EXPOSE 80 443


COPY rootfs/nginx/conf       /nginx/conf 
RUN ls -la /nginx/conf/*

ENTRYPOINT []
CMD [ "nginx" ,"-c", "/nginx/conf/nginx.conf" ]
