version: "3"
services:
  app:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    hostname: gitlab-runner    
    restart: always
    volumes:
      - /dockerdata/gitlab-runner/config:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
