version: "3"

services:
    nexus:
        restart: always
        image: sonatype/nexus3
        container_name: nexus3
        hostname: nexus
        ports:
            - 8081:8081
            - 8082:8082
            - 8083:8083
        volumes:
            - /dockerdata/nexus-data:/nexus-data:Z
        networks:
            - net1            
networks:
  net1:
    driver: bridge