version: "3"
services:
  clustercontrol:
    image: severalnines/clustercontrol
    hostname: clustercontrol
    privileged: true
    volumes:
    - dockerdata/clustercontrol/cmon.d:/etc/cmon.d
    - dockerdata/clustercontrol/sshkey:/root/.ssh
    - dockerdata/clustercontrol/cmonlib:/var/lib/cmon
    - dockerdata/clustercontrol/cmon.d:/etc/cmon.d
    - dockerdata/clustercontrol/backups:/root/backups
    ports:
    - "5000:80"
    - "5001:443"