version: "3"

services:
  postgres:
    image: postgres:alpine   #postgres 镜像
    restart: always
    container_name: postgres
    hostname: postgres   
    privileged: true #解决权限
    ports:
      - 5432:5432  #映射端口号
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dockerdata/postgres:/var/lib/postgresql:Z #将数据映射到对应的路径
    environment:
      - POSTGRES_PASSWORD=pgadmin123456  #密码
      - POSTGRES_USER:=pgadmin
      - PGDATA=/var/lib/postgresql/data/pgdata #数据存储文件夹
      - POSTGRES_DB=mydb
    networks:
      - dev-net
networks:
  dev-net:
    external: true
